apiVersion: v1
kind: Secret
metadata:
  name: sosmed-rds-secret
  namespace: production
type: Opaque
stringData:
  DB_NAME: "productionsosmed"
  DB_USER: "admin"
  DB_PASS: "1234567890"
  DB_HOST: sosmed.ceptw8s3gfho.ap-southeast-2.rds.amazonaws.com

  